# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in forthic.gemspec
gemspec

gem "rake", "~> 13.0"

group :development do
  gem "guard"
  gem "guard-minitest"
  gem "minitest-reporters"
  gem "minitest", "~> 5.16"
  gem "standard", "~> 1.3"
end
